baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Portfolio"
theme = "SimpleIntro"
publishDir = "public"

[params]
    mainbg = "https://picsum.photos/1920/1080"
    name = "Nina Zhang"
    mainTitle = "Hi there!"
    mainText = "3rd year software engineering student..."

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About Me"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"